spring:
  profiles:
    active: local

---
#local 환경
spring:
  profiles: local
  kafka:
    bootstrap-servers: 192.168.56.102:9092,192.168.56.102:9093,192.168.56.102:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 0
      #batch-size: 1000



---
#qa 환경
spring:
  profiles: qa
  kafka:
    bootstrap-servers: 192.168.56.102:9092,192.168.56.102:9093,192.168.56.102:9094